<string>.aliases</string>
<string>.bash_profile</string>
<string>.bash_prompt</string>
<string>.bashrc</string>
<string>.brew</string>
<string>.config</string>
<string>.exports</string>
<string>.functions</string>
<string>.git</string>
<string>.gitattributes</string>
<string>.gitconfig</string>
<string>.gitignore</string>
<string>.gitignore_global</string>
<string>.inputrc</string>
<string>.osx</string>
<string>.zshrc</string>
<string>.vim</string>
<string>.vimrc</string>
